### ISSUE TITLE
Settings will not open/Gui unresponsive

### ISSUE THREAD

**Issue by lolman9998** [jkotra/eOVPN#42]
Just installed and the ui doesn't seem to be working. Have tried rebooting, and, after looking at other issues installing libsecret.
CLI Output -
```
eovpn
cannot import openvpn3

(eovpn:15538): Gtk-WARNING **: 17:14:58.114: Unknown key gtk-modules in /home/paytonb/.config/gtk-4.0/settings.ini
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/eovpn/main_window.py", line 149, in <lambda>
    btn.connect("clicked", lambda x: SettingsWindow().show())
                                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/eovpn/settings_window.py", line 327, in show
    self.setup()
  File "/usr/lib/python3.11/site-packages/eovpn/settings_window.py", line 284, in setup
    version = NetworkManager(None).version()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/eovpn/connection_manager.py", line 132, in version
    return self.to_string(version, True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/eovpn/connection_manager.py", line 63, in to_string
    _str = self.ffi.string(data)
           ^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot use string() on <cdata 'char *' NULL>
```
I can confirm openvpn is installed.
More info - Arch Linux (Just reinstalled a couple days ago, fresh)
Kde wayland
Installed from AUR via yay

I can provide more info if needed. Thanks!

**Comment by lolman9998** [comment]
Just realized i forgot to run with --debug.
```
eovpn --debug 10
cannot import openvpn3

(eovpn:15865): Gtk-WARNING **: 17:21:11.824: Unknown key gtk-modules in /home/paytonb/.config/gtk-4.0/settings.ini
DEBUG:eovpn.eovpn_base.py:get_setting:dark-theme False
DEBUG:eovpn.eovpn_base.py:get_setting:manager networkmanager
DEBUG:eovpn.eovpn_base.py:get_setting:layout card-h
DEBUG:eovpn.eovpn_base.py:get_setting:show-flag False
DEBUG:eovpn.eovpn_base.py:get_setting:layout card-h
DEBUG:eovpn.eovpn_base.py:get_setting:last-connected-cursor -1
DEBUG:eovpn.ip_lookup.lookup.py:cloudflare:Cloudflare: k = fl | v = 658f55
DEBUG:eovpn.ip_lookup.lookup.py:cloudflare:Cloudflare: k = h | v = 104.16.123.96
DEBUG:eovpn.ip_lookup.lookup.py:cloudflare:Cloudflare: k = ip | v = 173.29.111.29
DEBUG:eovpn.ip_lookup.lookup.py:cloudflare:Cloudflare: k = ts | v = 1691101271.949
DEBUG:eovpn.ip_lookup.lookup.py:cloudflare:Cloudflare: k = visit_scheme | v = http
DEBUG:eovpn.ip_lookup.lookup.py:cloudflare:Cloudflare: k = uag | v = Python-urllib/3.11
DEBUG:eovpn.ip_lookup.lookup.py:cloudflare:Cloudflare: k = colo | v = ORD
DEBUG:eovpn.ip_lookup.lookup.py:cloudflare:Cloudflare: k = sliver | v = 005-tier1
DEBUG:eovpn.ip_lookup.lookup.py:cloudflare:Cloudflare: k = http | v = http/1.1
DEBUG:eovpn.ip_lookup.lookup.py:cloudflare:Cloudflare: k = loc | v = US
DEBUG:eovpn.ip_lookup.lookup.py:cloudflare:Cloudflare: k = tls | v = off
DEBUG:eovpn.ip_lookup.lookup.py:cloudflare:Cloudflare: k = sni | v = off
DEBUG:eovpn.ip_lookup.lookup.py:cloudflare:Cloudflare: k = warp | v = off
DEBUG:eovpn.ip_lookup.lookup.py:cloudflare:Cloudflare: k = gateway | v = off
DEBUG:eovpn.ip_lookup.lookup.py:cloudflare:Cloudflare: k = rbi | v = off
DEBUG:eovpn.ip_lookup.lookup.py:cloudflare:Cloudflare: k = kex | v = none
DEBUG:eovpn.eovpn_base.py:get_setting:remote None
DEBUG:eovpn.eovpn_base.py:get_setting:req-auth False
DEBUG:eovpn.eovpn_base.py:get_setting:auth-user None
DEBUG:eovpn.eovpn_base.py:get_setting:auth-user None
DEBUG:eovpn.eovpn_base.py:get_setting:ca None
DEBUG:eovpn.eovpn_base.py:get_setting:notifications True
DEBUG:eovpn.eovpn_base.py:get_setting:show-flag False
DEBUG:eovpn.eovpn_base.py:get_setting:dark-theme False
DEBUG:eovpn.eovpn_base.py:get_setting:manager networkmanager
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/eovpn/main_window.py", line 149, in <lambda>
    btn.connect("clicked", lambda x: SettingsWindow().show())
                                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/eovpn/settings_window.py", line 327, in show
    self.setup()
  File "/usr/lib/python3.11/site-packages/eovpn/settings_window.py", line 284, in setup
    version = NetworkManager(None).version()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/eovpn/connection_manager.py", line 132, in version
    return self.to_string(version, True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/eovpn/connection_manager.py", line 63, in to_string
    _str = self.ffi.string(data)
           ^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot use string() on <cdata 'char *' NULL>

```

**Comment by jkotra** [comment]
did you install openvpn plugin for NetworkManager?

`yay -S networkmanager-openvpn`

**Comment by lolman9998** [comment]
yes, i have it installed. reinstalled for good measure, still nothing.

**Comment by jkotra** [comment]
looks like i didn't update AUR with bug fix point release. Pushed now. please update @lolman9998.

**Comment by lolman9998** [comment]
Issue still occurs. Heres another log in case something changed.
```
eovpn
cannot import openvpn3

(eovpn:2018): Gtk-WARNING **: 16:08:17.329: Unknown key gtk-modules in /home/paytonb/.config/gtk-4.0/settings.ini
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/eovpn/main_window.py", line 149, in <lambda>
    btn.connect("clicked", lambda x: SettingsWindow().show())
                                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/eovpn/settings_window.py", line 327, in show
    self.setup()
  File "/usr/lib/python3.11/site-packages/eovpn/settings_window.py", line 284, in setup
    version = NetworkManager(None).version()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/eovpn/connection_manager.py", line 132, in version
    return self.to_string(version, True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/eovpn/connection_manager.py", line 63, in to_string
    _str = self.ffi.string(data)
           ^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot use string() on <cdata 'char *' NULL>
[paytonb@archlinux ~]$ eovpn --debug 10
cannot import openvpn3

(eovpn:2068): Gtk-WARNING **: 16:08:34.926: Unknown key gtk-modules in /home/paytonb/.config/gtk-4.0/settings.ini
DEBUG:eovpn.eovpn_base.py:get_setting:dark-theme False
DEBUG:eovpn.eovpn_base.py:get_setting:manager networkmanager
DEBUG:eovpn.eovpn_base.py:get_setting:layout card-h
DEBUG:eovpn.eovpn_base.py:get_setting:show-flag False
DEBUG:eovpn.eovpn_base.py:get_setting:layout card-h
DEBUG:eovpn.eovpn_base.py:get_setting:last-connected-cursor -1
DEBUG:eovpn.ip_lookup.lookup.py:cloudflare:Cloudflare: k = fl | v = 658f188
DEBUG:eovpn.ip_lookup.lookup.py:cloudflare:Cloudflare: k = h | v = 104.16.123.96
DEBUG:eovpn.ip_lookup.lookup.py:cloudflare:Cloudflare: k = ip | v = 173.29.111.29
DEBUG:eovpn.ip_lookup.lookup.py:cloudflare:Cloudflare: k = ts | v = 1691269715.057
DEBUG:eovpn.ip_lookup.lookup.py:cloudflare:Cloudflare: k = visit_scheme | v = http
DEBUG:eovpn.ip_lookup.lookup.py:cloudflare:Cloudflare: k = uag | v = Python-urllib/3.11
DEBUG:eovpn.ip_lookup.lookup.py:cloudflare:Cloudflare: k = colo | v = ORD
DEBUG:eovpn.ip_lookup.lookup.py:cloudflare:Cloudflare: k = sliver | v = 010-tier1
DEBUG:eovpn.ip_lookup.lookup.py:cloudflare:Cloudflare: k = http | v = http/1.1
DEBUG:eovpn.ip_lookup.lookup.py:cloudflare:Cloudflare: k = loc | v = US
DEBUG:eovpn.ip_lookup.lookup.py:cloudflare:Cloudflare: k = tls | v = off
DEBUG:eovpn.ip_lookup.lookup.py:cloudflare:Cloudflare: k = sni | v = off
DEBUG:eovpn.ip_lookup.lookup.py:cloudflare:Cloudflare: k = warp | v = off
DEBUG:eovpn.ip_lookup.lookup.py:cloudflare:Cloudflare: k = gateway | v = off
DEBUG:eovpn.ip_lookup.lookup.py:cloudflare:Cloudflare: k = rbi | v = off
DEBUG:eovpn.ip_lookup.lookup.py:cloudflare:Cloudflare: k = kex | v = none
DEBUG:eovpn.eovpn_base.py:get_setting:remote None
DEBUG:eovpn.eovpn_base.py:get_setting:req-auth False
DEBUG:eovpn.eovpn_base.py:get_setting:auth-user None
DEBUG:eovpn.eovpn_base.py:get_setting:auth-user None
DEBUG:eovpn.eovpn_base.py:get_setting:ca None
DEBUG:eovpn.eovpn_base.py:get_setting:notifications True
DEBUG:eovpn.eovpn_base.py:get_setting:show-flag False
DEBUG:eovpn.eovpn_base.py:get_setting:dark-theme False
DEBUG:eovpn.eovpn_base.py:get_setting:manager networkmanager
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/eovpn/main_window.py", line 149, in <lambda>
    btn.connect("clicked", lambda x: SettingsWindow().show())
                                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/eovpn/settings_window.py", line 327, in show
    self.setup()
  File "/usr/lib/python3.11/site-packages/eovpn/settings_window.py", line 284, in setup
    version = NetworkManager(None).version()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/eovpn/connection_manager.py", line 132, in version
    return self.to_string(version, True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/eovpn/connection_manager.py", line 63, in to_string
    _str = self.ffi.string(data)
           ^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot use string() on <cdata 'char *' NULL>

```

**Comment by jkotra** [comment]
do you have `libnm` package installed?

as a last resort, give a list of all your packages so that i can replicate your build on a VM.

**Comment by lolman9998** [comment]
Libnm is installed.
Base arch repos - 
```
amd-ucode 20230625.ee91452d-5
ark 23.04.3-1
base 3-1
base-devel 1-1
btrfs-progs 6.3.3-1
dolphin 23.04.3-1
efibootmgr 18-2
egl-wayland 2:1.1.12-1
eovpn 1.28.1-1
firefox 116.0.1-1
flatpak 1:1.15.4-1
git 2.41.0-2
gparted 1.5.0-1
gst-plugin-pipewire 1:0.3.76-2
htop 3.2.2-1
iwd 2.7-1
kate 23.04.3-1
konsole 23.04.3-1
libpulse 16.1-6
libva-mesa-driver 1:23.1.5-1
linux 6.4.8.arch1-1
linux-firmware 20230625.ee91452d-5
nano 7.2-1
neofetch 7.1.0-2
openssh 9.3p2-1
pipewire 1:0.3.76-2
pipewire-alsa 1:0.3.76-2
pipewire-jack 1:0.3.76-2
pipewire-pulse 1:0.3.76-2
plasma-meta 5.27-3
plasma-wayland-session 5.27.7-1
protontricks 1.10.3-1
protonup-qt 2.8.1-1
sddm 0.20.0-2
smartmontools 7.4-1
steam 1.0.0.78-1
steamtinkerlaunch 12.12-1
testdisk 7.1-5
timeshift 23.07.1-2
vim 9.0.1676-1
vulkan-radeon 1:23.1.5-1
wget 1.21.4-1
wireless_tools 30.pre9-3
wireplumber 0.4.14-1
wpa_supplicant 2:2.10-8
xdg-utils 1.1.3+25+g8ae0263-1
xf86-video-amdgpu 23.0.0-1
xf86-video-ati 1:22.0.0-1
xorg-server 21.1.8-2
xorg-xinit 1.4.2-1
yay 12.1.2-1
zram-generator 1.1.2-1
```
AUR -
```
eovpn
openvpn3
protontricks
protonup-qt
python-gevent-eventemitter
python-inputs
python-steam
python-vdf
steamtinkerlaunch
yay
```
Flatpak -
```
Name                     Application ID                          Version      Branch         Installation
Discord                  com.discordapp.Discord                  0.0.28       stable         system
Freedesktop Platform     org.freedesktop.Platform                22.08.14     22.08          system
Mesa                     org.freedesktop.Platform.GL.default     23.1.4       22.08          system
Mesa (Extra)             org.freedesktop.Platform.GL.default     23.1.4       22.08-extra    system
openh264                 org.freedesktop.Platform.openh264       2.1.0        2.2.0          system
```
Should be all of it. Lemme know if anything seems off so I can fix it.

**Comment by lolman9998** [comment]
[packages.txt](https://github.com/jkotra/eOVPN/files/12268295/packages.txt)
Found out it wasn't finding all of them, heres a more complete list

**Comment by jkotra** [comment]
I was too busy IRL to setup and test.. might take a while. Apologies.

I tried installing `eovpn` directly from AUR with `yay -S eovpn` and it worked right correctly.

https://github.com/jkotra/eOVPN/blob/5713cf1044b2f59f73b27f7af8897f91e307c2bd/subprojects/networkmanager/eovpn_nm.c#L387-L393

My guess is that `nm_client_get_version` is returning `null` for reasons unknown.

If you would like to dig deeper yourself, take a look at [eovpn_nm.c](https://github.com/jkotra/eOVPN/blob/1.28.1/subprojects/networkmanager/eovpn_nm.c).  It can be compiled as standalone single filw and you can find building instructions with GCC at top comment. (un-comment the `main()` at bottom)

**Comment by Pijuten** [comment]
same issue

**Comment by Pijuten** [comment]
> same issue

For me it works on kde-plasma, but on i3wm I have the issue

**Comment by valerii15298** [comment]
I had the same problem and found a solution. You need NetworkManager to be installed and running. If you do not have it - install it. If it is not enabled or not running just do:
```bash
sudo systemctl enable NetworkManager.service
sudo systemctl start NetworkManager.service
```

This should fix the problem

**Comment by panic-canine** [comment]
I was having issues using iwd as a backend. Disabling it fixed it for me

**Comment by PIKUT0** [comment]
> I had the same problem and found a solution. You need NetworkManager to be installed and running. If you do not have it - install it. If it is not enabled or not running just do:
> 
> ```shell
> sudo systemctl enable NetworkManager.service
> sudo systemctl start NetworkManager.service
> ```
> 
> This should fix the problem

Yup, it works. Close the issue :>
