### ISSUE TITLE
Does not connect

### ISSUE THREAD

**Issue by Broly1** [jkotra/eOVPN#43]
[broly@archlinux ~]$ flatpak run com.github.jkotra.eovpn
Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/eovpn/main_window.py", line 465, in connect
    manager.connect(os.path.join(self.EOVPN_CONFIG_DIR, "CONFIGS", config))
  File "/app/lib/python3.10/site-packages/eovpn/connection_manager.py", line 95, in connect
    uuid = self.nm_manager.add_connection(str(tmp_config).encode("utf-8"),
TypeError: initializer for ctype 'char *' must be a cdata pointer, not NoneType

**Comment by Ugric** [comment]
getting a slightly different error but its being caused by the same line:

Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/eovpn/main_window.py", line 465, in connect
    manager.connect(os.path.join(self.EOVPN_CONFIG_DIR, "CONFIGS", config))
  File "/usr/lib/python3.10/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.10/genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'
